# ========================================
# ⚡ МИНИМАЛЬНАЯ КОНФИГУРАЦИЯ HLK-LD2402
# ========================================
# Используйте для повседневного использования
# после завершения калибровки.
#
# Включает только необходимые датчики:
# - Присутствие
# - Микродвижения
# - Расстояние
# - Помехи по питанию
# - Базовые кнопки управления
# ========================================

# Базовые настройки ESPHome - настройте под своё устройство
esphome:
  name: radar-sensor
  friendly_name: Датчик Радара

esp32:
  board: esp32dev

# Включаем API Home Assistant
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Включаем резервную точку доступа при сбое WiFi
  ap:
    ssid: "Radar-Sensor Fallback"
    password: !secret fallback_password

logger:
  level: INFO

# Конфигурация UART для HLK-LD2402
uart:
  id: uart_bus
  tx_pin: GPIO1 # TX0 аппаратный UART
  rx_pin: GPIO3 # RX0 аппаратный UART
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Компонент радара HLK-LD2402
external_components:
  - source:
      type: git
      url: https://github.com/mihazzz123/hlk_ld2402_esphome.git
    refresh: 0ms

hlk_ld2402:
  uart_id: uart_bus
  id: radar_sensor
  max_distance: 5.0
  timeout: 5

# Бинарные датчики - только основные
binary_sensor:
  # Обнаружение присутствия - показывает, есть ли кто-то в зоне обнаружения
  - platform: hlk_ld2402
    id: radar_presence
    name: "Присутствие"
    device_class: presence
    hlk_ld2402_id: radar_sensor

  # Обнаружение микродвижений - показывает, обнаружены ли малые движения
  - platform: hlk_ld2402
    id: radar_micromovement
    name: "Микродвижения"
    device_class: motion
    hlk_ld2402_id: radar_sensor

  # Обнаружение помех по питанию - показывает, вызывает ли источник питания помехи
  - platform: hlk_ld2402
    id: radar_power_interference
    name: "Помехи по питанию"
    device_class: problem
    power_interference: true
    hlk_ld2402_id: radar_sensor

# Датчик расстояния - показывает, как далеко находится обнаруженный человек
sensor:
  - platform: hlk_ld2402
    id: radar_distance
    name: "Расстояние"
    hlk_ld2402_id: radar_sensor
    device_class: distance
    unit_of_measurement: "см"
    accuracy_decimals: 1
    throttle: 2000ms # Интервал 2 секунды для более плавных показаний

# Включаем только основную кнопку калибровки
button:
  - platform: template
    name: "Калибровка"
    icon: "mdi:radar"
    on_press:
      - lambda: id(radar_sensor).calibrate();

  # Кнопка сохранения после калибровки или изменения порогов
  - platform: template
    name: "Сохранить конфигурацию"
    icon: "mdi:content-save"
    on_press:
      - lambda: id(radar_sensor).save_config();

# Опционально - Добавьте светодиод состояния, если доступен
status_led:
  pin: GPIO2
